import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto_Mono({ subsets: ["latin"],
weight: ["400", "100", "700"] });

export const robotoMono: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="pt-br">
        <body className={` ${roboto.className}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
